---
# Namespace for the portfolio application
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: anyuid
users:
  - system:serviceaccount:dev:default


---
# ConfigMap for static HTML content
apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-html
  namespace: dev
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Portfolio</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
        h1 { color: #333; }
        p { font-size: 18px; }
      </style>
    </head>
    <body>
      <h1>Welcome to My Portfolio</h1>
      <p>This is a static portfolio site deployed on OpenShift using Nginx and managed by ArgoCD.</p>
      <p>Created by Komlan</p>
    </body>
    </html>

---
# Deployment for the Nginx-based portfolio app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: dev
  labels:
    app: portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:latest  # Use nginx:latest or a custom image
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: portfolio-html

---
# Service to expose the portfolio app internally
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: dev
spec:
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---
# Route to expose the portfolio app externally
 apiVersion: route.openshift.io/v1
 kind: Route
 metadata:
   name: portfolio-route
   namespace: dev
 spec:
   host: portfolio.itssolutions.tech
   to:
     kind: Service
     name: portfolio-service
   port:
     targetPort: 80
   tls:
     termination: edge  # Enables HTTPS