

---
# ConfigMap for static HTML content
apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-html
  namespace: dev
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Komlan Florient Dogbe - DevOps & SRE Expert</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
                background-color: #f4f4f4;
                text-align: center;
            }
            .container {
                max-width: 800px;
                margin: 20px auto;
                padding: 20px;
                background-color: #fff;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }
            img {
                width: 150px;
                border-radius: 50%;
            }
            h1 {
                color: #333;
            }
            p {
                color: #555;
            }
            .links a {
                display: inline-block;
                margin: 10px;
                padding: 10px 15px;
                background: #0073e6;
                color: #fff;
                text-decoration: none;
                border-radius: 5px;
            }
            .links a:hover {
                background: #005bb5;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <img src="https://tse2.mm.bing.net/th?id=OIP.Ee5bbFa_GfghVs2L2OhhowAAAA&pid=Api" alt="Komlan Florient Dogbe">
            <h1>Komlan Florient Dogbe</h1>
            <h2>DevOps | SRE | DevSecOps | Red Hat Architect</h2>
            <p>
                Komlan Florient Dogbe is a seasoned professional specializing in Site Reliability Engineering (SRE), DevOps, and DevSecOps.
                With experience as a Site Reliability Engineer, DevOps Consultant, DevSecOps/SOC Analyst, Co-founder and CTO, and Assistant Professor,
                he has a strong background in automation, security, and cloud computing.
            </p>
            <p>
                He holds the <strong>Red Hat Certified Specialist in Building Resilient Microservices</strong> certification, 
                proving his expertise in creating scalable and robust architectures.
            </p>
            <div class="links">
                <a href="https://de.linkedin.com/in/komlan-florient-dogbe-redhat-architect" target="_blank">LinkedIn</a>
                <a href="https://github.com/florient2016" target="_blank">GitHub</a>
            </div>
        </div>
    </body>
    </html>
    

---
# Deployment for the Nginx-based portfolio app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: dev
  labels:
    app: portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:latest  # Use nginx:latest or a custom image
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: portfolio-html

---
# Service to expose the portfolio app internally
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: dev
spec:
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---
# Route to expose the portfolio app externally
 apiVersion: route.openshift.io/v1
 kind: Route
 metadata:
   name: portfolio-route
   namespace: dev
 spec:
   #host: portfolio.itssolutions.tech
   to:
     kind: Service
     name: portfolio-service
   port:
     targetPort: 80
   tls:
     termination: edge  # Enables HTTPS