apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anyuid-default-dev  # Unique name for the binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: dev
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid  # References the anyuid SCC
  apiGroup: rbac.authorization.k8s.io