
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-scc-role
  namespace: nfs-provisioner
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privileged-scc-binding
  namespace: nfs-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: privileged-scc-role
subjects:
- kind: ServiceAccount
  name: nfs-client-provisioner
  namespace: nfs-provisioner