apiVersion: v1
kind: PersistentVolume
metadata:
  name: aap-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shares/registry
    server: 10.10.0.2